// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package repository

import (
	"context"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (tour_id, customer_name, customer_email, customer_phone, num_people)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tour_id, customer_name, customer_email, customer_phone, num_people, status, created_at
`

type CreateBookingParams struct {
	TourID        int32  `json:"tour_id"`
	CustomerName  string `json:"customer_name"`
	CustomerEmail string `json:"customer_email"`
	CustomerPhone string `json:"customer_phone"`
	NumPeople     int32  `json:"num_people"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.TourID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.NumPeople,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.NumPeople,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, tour_id, customer_name, customer_email, customer_phone, num_people, status, created_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.NumPeople,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const tourExists = `-- name: TourExists :one
SELECT EXISTS(SELECT 1 FROM tours WHERE id = $1)
`

func (q *Queries) TourExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, tourExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
