// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID            int32              `json:"id"`
	TourID        int32              `json:"tour_id"`
	CustomerName  string             `json:"customer_name"`
	CustomerEmail string             `json:"customer_email"`
	CustomerPhone string             `json:"customer_phone"`
	NumPeople     int32              `json:"num_people"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Country struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

type Tour struct {
	ID           int32              `json:"id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	CountryID    int32              `json:"country_id"`
	Price        pgtype.Numeric     `json:"price"`
	Currency     string             `json:"currency"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	DurationDays int32              `json:"duration_days"`
	Category     pgtype.Text        `json:"category"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
