// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CountTours(ctx context.Context, arg CountToursParams) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	GetBooking(ctx context.Context, id int32) (Booking, error)
	GetTour(ctx context.Context, id int32) (Tour, error)
	ListCountries(ctx context.Context) ([]Country, error)
	ListTours(ctx context.Context, arg ListToursParams) ([]Tour, error)
	TourExists(ctx context.Context, id int32) (bool, error)
}

var _ Querier = (*Queries)(nil)
