// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tours.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTours = `-- name: CountTours :one
SELECT count(*)
FROM tours
WHERE
  ($1::int IS NULL OR country_id = $1)
  AND ($2::numeric IS NULL OR price >= $2)
  AND ($3::numeric IS NULL OR price <= $3)
  AND ($4::date IS NULL OR end_date >= $4)
  AND ($5::date IS NULL OR start_date <= $5)
`

type CountToursParams struct {
	CountryID pgtype.Int4    `json:"country_id"`
	MinPrice  pgtype.Numeric `json:"min_price"`
	MaxPrice  pgtype.Numeric `json:"max_price"`
	DateFrom  pgtype.Date    `json:"date_from"`
	DateTo    pgtype.Date    `json:"date_to"`
}

func (q *Queries) CountTours(ctx context.Context, arg CountToursParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTours,
		arg.CountryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTour = `-- name: GetTour :one
SELECT id, title, description, country_id, price, currency, start_date, end_date, duration_days, category, image_url, created_at FROM tours WHERE id = $1
`

func (q *Queries) GetTour(ctx context.Context, id int32) (Tour, error) {
	row := q.db.QueryRow(ctx, getTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CountryID,
		&i.Price,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.DurationDays,
		&i.Category,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listTours = `-- name: ListTours :many
SELECT id, title, description, country_id, price, currency, start_date, end_date, duration_days, category, image_url, created_at
FROM tours
WHERE
  ($1::int IS NULL OR country_id = $1)
  AND ($2::numeric IS NULL OR price >= $2)
  AND ($3::numeric IS NULL OR price <= $3)
  AND ($4::date IS NULL OR end_date >= $4)
  AND ($5::date IS NULL OR start_date <= $5)
ORDER BY start_date ASC, id ASC
LIMIT $7
OFFSET $6
`

type ListToursParams struct {
	CountryID pgtype.Int4    `json:"country_id"`
	MinPrice  pgtype.Numeric `json:"min_price"`
	MaxPrice  pgtype.Numeric `json:"max_price"`
	DateFrom  pgtype.Date    `json:"date_from"`
	DateTo    pgtype.Date    `json:"date_to"`
	Offset    int32          `json:"offset"`
	Limit     int32          `json:"limit"`
}

func (q *Queries) ListTours(ctx context.Context, arg ListToursParams) ([]Tour, error) {
	rows, err := q.db.Query(ctx, listTours,
		arg.CountryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.DateFrom,
		arg.DateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tour
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CountryID,
			&i.Price,
			&i.Currency,
			&i.StartDate,
			&i.EndDate,
			&i.DurationDays,
			&i.Category,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
